events {}

http {
    upstream backend {
        least_conn;
        server ai-health-bot:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
}